/* MMO-role scoring quiz. Class is scored first; subclass is then chosen only within the winning class. */
const QUESTIONS=[
{t:'Your party faces a large group of weaker enemies. What role do you want?',a:[['Delete as many targets as possible with AoE damage.',{Wizard:3,Sorcerer:3,Druid:2},{'Wizard:School of Evocation':3,'Druid:Circle of Wildfire':2}],['Lock enemies down so the party can deal with them safely.',{Wizard:3,Bard:2,Cleric:1},{'Wizard:School of Enchantment':3,'Wizard:School of Illusion':2}],['Rush into the middle and survive while enemies focus on me.',{Barbarian:3,Fighter:3,Paladin:2},{'Barbarian:Path of the Totem Warrior':2,'Fighter:Cavalier':2,'Paladin:Oath of the Crown':2}],['Keep the group alive while contributing damage.',{Cleric:3,Druid:2,Bard:2},{'Cleric:Life Domain':3,'Druid:Circle of Dreams':2,'Bard:College of Encouragement':2}]]},
{t:'A boss has a huge amount of HP. What sounds most satisfying?',a:[['Consistent single-target DPR every round.',{Fighter:3,Rogue:3,Ranger:2},{'Fighter:Battle Master':2,'Rogue:Assassin':2,'Ranger:Hunter':1}],['Set up a huge burst window and unload.',{Rogue:3,Paladin:3,Sorcerer:2},{'Rogue:Assassin':3,'Paladin:Oath of Vengeance':3}],['Exploit weaknesses with spells, debuffs, and control.',{Wizard:3,Warlock:2,Bard:2},{'Wizard:Graviturgy Magic':2,'Warlock:The Great Old One':2}],['Keep everyone buffed and make the whole party perform better.',{Bard:3,Cleric:2,Paladin:2},{'Bard:College of Leadership':3,'Cleric:Peace Domain':2}]]},
{t:'Which MMO-style role sounds most like your ideal job?',a:[['Tank — absorb pressure and control enemy attention.',{Barbarian:3,Fighter:3,Paladin:3},{'Barbarian:Path of the Ancestral Guardian':3,'Fighter:Cavalier':3,'Paladin:Oath of the Crown':3}],['Healer — keep the party alive through sustained damage.',{Cleric:4,Druid:3,Bard:2},{'Cleric:Life Domain':4,'Druid:Circle of Dreams':2}],['DPS — maximize personal damage and kill targets quickly.',{Rogue:3,Fighter:3,Ranger:2,Sorcerer:2},{'Rogue:Soulknife':2,'Fighter:Titan':3,'Ranger:Gloom Stalker':2}],['Utility — bring tools that solve whatever the encounter throws at us.',{Bard:3,Artificer:3,Wizard:3,Rogue:2},{'Bard:College of Lore':2,'Artificer:Researcher':3,'Wizard:Order of Scribes':2}]]},
{t:'How important is AoE to your build?',a:[['Extremely important. I want AoE to define my build.',{Wizard:3,Sorcerer:3,Druid:3},{'Wizard:School of Evocation':3,'Sorcerer:Soundboost':2,'Druid:Circle of Drakes':3}],['Useful, but I primarily care about single-target damage.',{Rogue:2,Fighter:2,Ranger:2},{'Rogue:Shadow Archer':2,'Fighter:Titan':2,'Ranger:Monster Slayer':2}],['I care more about AoE control than AoE damage.',{Wizard:3,Bard:3,Druid:2},{'Wizard:School of Illusion':2,'Bard:College of Eloquence':2}],['AoE is nice, but I would rather improve my party.',{Cleric:3,Bard:2,Paladin:2},{'Cleric:Peace Domain':2,'Bard:College of Encouragement':2}]]},
{t:'Your party has a problem outside combat. What do you contribute?',a:[['Information, skills, social manipulation, or scouting.',{Rogue:3,Bard:3,Ranger:1},{'Rogue:Inquisitive':3,'Bard:College of Eloquence':3}],['A huge toolbox of spells and magical solutions.',{Wizard:4,Artificer:2,Cleric:1},{'Wizard:Order of Scribes':3,'Wizard:School of Transmutation':2,'Artificer:Researcher':2}],['Healing, protection, or support abilities.',{Cleric:3,Druid:2,Paladin:2},{'Cleric:Peace Domain':2,'Paladin:Oath of Hearth':3}],['I want to handle the physical problem directly.',{Fighter:2,Barbarian:2,Monk:2,Ranger:2},{'Fighter:Battle Master':2,'Barbarian:Path of the Beast':2,'Monk:Way of the Open Hand':2}]]},
{t:'Which combat utility matters most?',a:[['Mobility — reposition constantly and reach priority targets.',{Monk:3,Rogue:3,Ranger:2},{'Monk:Way of Shadow':3,'Rogue:Swashbuckler':2,'Ranger:Horizon Walker':2}],['Crowd control — stun, charm, slow, banish, or disrupt.',{Wizard:3,Bard:3,Warlock:2,Monk:2},{'Wizard:School of Enchantment':3,'Bard:College of Glamour':2,'Warlock:The Fathomless':2}],['Defense — prevent damage or make the team harder to kill.',{Paladin:3,Cleric:3,Fighter:2,Sorcerer:2},{'Paladin:Oath of Redemption':3,'Cleric:Twilight Domain':3,'Sorcerer:Soul Shield':3}],['Debuffs — make enemies weaker so everyone deals more damage.',{Warlock:3,Bard:2,Cleric:2,Rogue:1},{'Warlock:The Hexblade':2,'Bard:College of Whispers':2,'Cleric:Grave Domain':3}]]},
{t:'How do you feel about RNG affecting your performance?',a:[['Love it. High rolls and unpredictable effects are exciting.',{Sorcerer:3,Barbarian:2,Rogue:2},{'Sorcerer:Wild Magic':4,'Barbarian:Path of Wild Magic':3,'Rogue:Outlaw':3}],['I want to manipulate RNG in my favor.',{Sorcerer:3,Wizard:2,Bard:2},{'Sorcerer:Fate':4,'Wizard:School of Divination':3}],['I want consistent, predictable performance.',{Fighter:3,Paladin:2,Cleric:2},{'Fighter:Champion':2,'Paladin:Oath of Devotion':2}],['Some RNG is fine if I have backup tools.',{Bard:3,Artificer:2,Rogue:2},{'Bard:College of Lore':2,'Artificer:Alchemist':2,'Rogue:Outlaw':2}]]},
{t:'Pick the damage profile you would most enjoy.',a:[['Massive AoE / spell damage.',{Wizard:3,Sorcerer:3,Druid:3},{'Wizard:School of Evocation':3,'Sorcerer:Soundboost':3,'Druid:Circle of Drakes':3}],['Close-range sustained physical damage.',{Barbarian:3,Monk:3,Fighter:3},{'Barbarian:Path of Frost':2,'Monk:Way of Lethality':3,'Fighter:Titan':3}],['Precision / burst damage against one target.',{Rogue:4,Ranger:2,Paladin:2},{'Rogue:Assassin':3,'Ranger:Monster Slayer':2,'Paladin:Oath of Vengeance':2}],['Damage plus meaningful support or control.',{Warlock:2,Cleric:3,Bard:3,Druid:2},{'Warlock:The Celestial':3,'Cleric:Grave Domain':2,'Bard:College of Spirits':2}]]},
{t:'Which encounter contribution sounds most satisfying?',a:[['Be the reliable backbone of the party.',{Fighter:3,Paladin:3,Cleric:2},{'Fighter:Champion':2,'Paladin:Oath of Devotion':3,'Cleric:Order Domain':2}],['Change the battlefield and dictate how enemies act.',{Wizard:4,Druid:3,Warlock:2,Monk:2},{'Wizard:Graviturgy Magic':3,'Warlock:The Fathomless':2}],['Make everyone around me better.',{Bard:4,Cleric:3,Paladin:2},{'Bard:College of Encouragement':3,'Bard:College of Leadership':3,'Cleric:Peace Domain':3}],['Hunt down the most dangerous target.',{Ranger:3,Rogue:3,Fighter:2,Paladin:2},{'Ranger:Monster Slayer':3,'Rogue:Assassin':2,'Paladin:Oath of Vengeance':3}]]},
{t:'If your build had a resource meter, what would you spend it on?',a:[['Big damage cooldowns.',{Sorcerer:3,Paladin:3,Fighter:2},{'Paladin:Oath of Vengeance':3,'Fighter:Battle Master':2}],['Defensive cooldowns and emergency survivability.',{Barbarian:3,Paladin:3,Fighter:2},{'Barbarian:Path of Rejuvenation':3,'Paladin:Oath of Redemption':2}],['Support abilities that improve everyone else.',{Bard:4,Cleric:2,Paladin:2},{'Bard:College of Leadership':3,'Bard:College of Encouragement':3}],['Flexible tools whose use changes by encounter.',{Artificer:3,Wizard:3,Druid:2},{'Artificer:Researcher':3,'Wizard:War Magic':2}]]}
];
const D={
Barbarian:[['Path of the Totem Warrior'],['Path of Wild Magic'],['Path of the Zealot'],['Path of the Battlerager'],['Path of the Berserker'],['Path of the Beast'],['Path of the Storm Herald'],['Path of the Ancestral Guardian'],['Path of Frost',1,'Infused with ice and empowered by cold damage.'],['Path of Rejuvenation',1,'Uses rage to heal themselves and their allies.'],['Path of Time',1,'Uses chronomancy to heal allies and support rolls.']],
Bard:[['College of Eloquence'],['College of Whispers'],['College of Spirits'],['College of Lore'],['College of Valor'],['College of Swords'],['College of Creation'],['College of Glamour'],['College of Encouragement',1,'Improves the party through Bardic Inspiration and better critical-hit opportunities.'],['College of Leadership',1,'Uses Bardic Inspiration for temporary HP, protection, and tanking support.']],
Cleric:[['War Domain'],['Grave Domain'],['Peace Domain'],['Tempest Domain'],['Light Domain'],['Trickery Domain'],['Death Domain'],['Twilight Domain'],['Arcana Domain'],['Forge Domain'],['Knowledge Domain'],['Entropy Domain'],['Nature Domain'],['Life Domain'],['Order Domain'],['Pestilence',1,'Uses poisons to deal heavy damage.']],
Druid:[['Circle of the Land (Coast)'],['Circle of Spores'],['Circle of Stars'],['Circle of Dreams'],['Circle of the Land (Forest)'],['Circle of the Land (Underdark)'],['Circle of the Land (Grassland)'],['Circle of the Land (Swamp)'],['Circle of the Land (Mountain)'],['Circle of the Land (Desert)'],['Circle of the Land (Arctic)'],['Circle of the Land'],['Circle of the Shepherd'],['Circle of Wildfire'],['Circle of the Moon'],['Circle of Fangs',1,'A Moon Druid variant focused purely on damage.'],['Circle of Fey',1,'Combines wild magic with monster wildshapes.'],['Circle of Drakes',1,'Dragon forms with a damage and AoE focus.']],
Fighter:[['Samurai'],['Echo Knight'],['Gunslinger'],['Eldritch Knight'],['Arcane Archer'],['Rune Knight'],['Psi Warrior'],['Cavalier'],['Champion'],['Purple Dragon Knight'],['Battle Master'],['Titan',1,'A very strong fighter who fights with two heavy weapons.'],['Soul Cleaver',1,'Uses souls to heal and deal ranged damage.']],
Monk:[['Way of the Drunken Master'],['Way of the Open Hand'],['Way of the Long Death'],['Way of the Ascendant Dragon'],['Way of Shadow'],['Way of Mercy'],['Way of the Four Elements'],['Way of the Cobalt Soul'],['Way of the Sun Soul'],['Way of the Astral Self'],['Way of the Kensei'],['Way of Lethality',1,'Uses daggers and bleeding effects.']],
Paladin:[['Oath of Vengeance'],['Oath of the Ancients'],['Oath of the Crown'],['Oath of Redemption'],['Oath of Glory'],['Oath of the Open Sea'],['Oath of the Watchers'],['Oath of Devotion'],['Oath of Conquest'],['Oathbreaker'],['Oath of Hearth',1,'Uses Lay on Hands for advanced healing.'],['Oath of Stability',1,'Cannot be banished and can exile foes into sub-planes.']],
Ranger:[['Fey Wanderer'],['Gloom Stalker'],['Monster Slayer'],['Swarmkeeper'],['Hunter'],['Beast Master'],['Drakewarden'],['Horizon Walker'],['Shelter Conclave',1,'Focuses on tanking and being the apex predator.'],['Royalty Conclave',1,'Focuses on complex magic used on people rather than beasts.']],
Rogue:[['Thief'],['Soulknife'],['Mastermind'],['Arcane Trickster'],['Phantom'],['Inquisitive'],['Scout'],['Swashbuckler'],['Assassin'],['Medic',1,'A Rogue focused on healing while incorporating Sneak Attack.'],['Outlaw',1,'Uses RNG rolls to gain different buffs.'],['Shadow Archer',1,'Uses advanced ranged techniques with Sneak Attack.']],
Sorcerer:[['Aberrant Mind'],['Divine Soul'],['Clockwork Soul'],['Storm Sorcery'],['Draconic Bloodline'],['Wild Magic'],['Shadow Magic'],['Fate',1,'Manipulates dice rolls and probability.'],['Soul Shield',1,'A tanky Sorcerer with increased AC and temporary HP.'],['Soundboost',1,'Uses thunder and sound-based damage.']],
Warlock:[['The Genie'],['The Hexblade'],['The Fiend'],['The Fathomless'],['The Undying'],['The Celestial'],['The Great Old One'],['The Archfey'],['The Undead'],['Arch Devil']],
Wizard:[['School of Illusion'],['School of Evocation'],['School of Necromancy'],['School of Abjuration'],['School of Conjuration'],['School of Enchantment'],['Graviturgy Magic'],['War Magic'],['School of Divination'],['Bladesinging'],['School of Transmutation'],['Chronurgy Magic'],['Order of Scribes'],['Transmogrification',1,'Uses polymorphs to become powerful, tanky beasts.']],
Artificer:[['Armorer'],['Battle Smith'],['Alchemist'],['Artillerist'],['Researcher',1,'Becomes a fullcaster focused on damaging magic with some support.']],
'Death Knight':{pool:'Paladin'}
};
const deathSubs=D.Paladin;
function subs(c){return D[c]?.pool?deathSubs:D[c]||[]}function add(o,x){for(const[k,v]of Object.entries(x||{}))o[k]=(o[k]||0)+v}function calc(){let c={},s={};QUESTIONS.forEach((q,i)=>{let x=state.answers[i];if(x==null)return;add(c,q.a[x][1]);add(s,q.a[x][2])});return{c,s}}function rank(o){return Object.entries(o).sort((a,b)=>b[1]-a[1]||a[0].localeCompare(b[0]))}
function result(){let z=calc(),r=rank(z.c),win=r[0]?.[0]||'Unknown',list=subs(win).map(x=>({n:x[0],v:z.s[win+':'+x[0]]||0,custom:!!x[1],d:x[2]||''})).sort((a,b)=>b.v-a.v||a.n.localeCompare(b.n));let sub=list[0]||{n:'No Clear Subclass Match',v:0,d:'Your class match is clear, but the answers did not distinguish a subclass.'};if(!sub.v)sub={n:'No Clear Subclass Match',v:0,d:'Your class match is clear, but the answers did not strongly distinguish between its subclasses.'};$('result-class').textContent=win;$('result-subclass').textContent=sub.n;$('result-description').textContent=sub.d||`Your answers most strongly matched the ${win} role profile.`;$('custom-badge').classList.toggle('hidden',!sub.custom);$('reasons').innerHTML=state.answers.map((x,i)=>x==null?'':`<li>${QUESTIONS[i].a[x][0]}</li>`).join('');let mx=Math.max(...r.map(x=>x[1]),1);$('breakdown').innerHTML=r.map(x=>`<div class="bar-row"><div class="bar-label"><span>${x[0]}</span><span>${x[1]}</span></div><div class="bar-track"><div class="bar-fill" style="width:${Math.max(2,x[1]/mx*100)}%"></div></div></div>`).join('');$('others').innerHTML=r.slice(1,5).map(x=>`<div class="match">${x[0]} — ${x[1]} points</div>`).join('');show('results-screen')}
const state={i:0,answers:Array(QUESTIONS.length).fill(null)};const $=id=>document.getElementById(id);function show(id){document.querySelectorAll('.screen').forEach(x=>x.classList.remove('active'));$(id).classList.add('active')}function render(){let q=QUESTIONS[state.i];$('question-number').textContent=`Question ${state.i+1}`;$('question-text').textContent=q.t;$('progress-label').textContent=`${state.i+1} / ${QUESTIONS.length}`;$('progress-bar').style.width=((state.i+1)/QUESTIONS.length*100)+'%';$('answers').innerHTML=q.a.map((x,j)=>`<button class="answer ${state.answers[state.i]===j?'selected':''}" data-i="${j}">${x[0]}</button>`).join('');document.querySelectorAll('.answer').forEach(b=>b.onclick=()=>{state.answers[state.i]=+b.dataset.i;render()});$('back-btn').disabled=state.i===0;$('next-btn').disabled=state.answers[state.i]===null;$('next-btn').textContent=state.i===QUESTIONS.length-1?'See Result':'Next'}$('start-btn').onclick=()=>{state.i=0;state.answers.fill(null);show('quiz-screen');render()};$('back-btn').onclick=()=>{if(state.i){state.i--;render()}};$('next-btn').onclick=()=>{if(state.i<QUESTIONS.length-1){state.i++;render()}else result()};$('restart-btn').onclick=()=>show('start-screen');
